version: '3'
services:
  calculator:
    image: bansalc73/calc_dev_ops123:latest
    ports:
      - "8080:80"
    # command: ["java", "-jar", "calculatorDevOps-1.0-SNAPSHOT-jar-with-dependencies.jar"]
    # stdin_open: true
    # tty: true